SELECT 
PS_PARTKEY, 
SUM(PS_SUPPLYCOST*PS_AVAILQTY) AS VALUE
FROM 
PARTSUPP, SUPPLIER, NATION
WHERE 
PS_SUPPKEY = S_SUPPKEY AND 
S_NATIONKEY = N_NATIONKEY AND 
N_NATIONKEY = 24
GROUP BY 
PS_PARTKEY
HAVING 
SUM(PS_SUPPLYCOST*PS_AVAILQTY) > SUM(PS_SUPPLYCOST*PS_AVAILQTY) * 0.0001000000
ORDER BY 
VALUE DESC;