SELECT 
	SUM(CASE 
		WHEN NATION = 'BRAZIL' THEN l_extendedprice * (1 - l_discount)
		ELSE 0
	    END)/SUM((l_extendedprice * (1 - l_discount))) AS MKT_SHARE,
	date_part('year', o_orderdate) as o_year
FROM
PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION, REGION
WHERE
P_PARTKEY = L_PARTKEY AND 
S_SUPPKEY = L_SUPPKEY AND 
L_ORDERKEY = O_ORDERKEY AND 
O_CUSTKEY = C_CUSTKEY AND 
C_NATIONKEY = N_NATIONKEY AND
N_REGIONKEY = R_REGIONKEY AND 
R_NAME = 'AMERICA' AND 
O_ORDERDATE BETWEEN date '1995-01-01' AND date '1996-12-31' AND 
P_TYPE = 'ECONOMY ANODIZED STEEL'
GROUP BY 
O_YEAR
ORDER BY 
O_YEAR;
