SELECT 
N_NAME as NATION, 
date_part('year', o_orderdate) as O_YEAR,
SUM(l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity) AS SUM_PROFIT
FROM 
PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
WHERE 
S_SUPPKEY = L_SUPPKEY AND 
PS_SUPPKEY= L_SUPPKEY AND 
PS_PARTKEY = L_PARTKEY AND
P_PARTKEY= L_PARTKEY AND 
O_ORDERKEY = L_ORDERKEY AND 
S_NATIONKEY = N_NATIONKEY AND
P_NAME LIKE '%green%'
GROUP BY 
NATION, O_YEAR
ORDER BY 
NATION, O_YEAR DESC;
